# Build stage
FROM golang:1.16-alpine AS builder

ADD . /app
WORKDIR /app

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o ./bin/http_server ./cmd/main.go

# Production stage
FROM alpine:latest
COPY --from=builder  /app/bin/http_server /
COPY --from=builder  /app/config /config

EXPOSE 8080
CMD [ "/http_server" ]