# Build stage
FROM golang:1.15-alpine AS builder

ADD . /app
WORKDIR /app

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /app/http_server main.go

# Production stage
FROM alpine:latest
COPY --from=builder  /app/http_server /

EXPOSE 8080
CMD [ "/http_server" ]